Fix compile errors on new added dash APIs
Why
After PR https://github.com/opencomputeproject/SAI/pull/1590, new added dash interfaces blocking saithriftv2 building, with errors like
```
../../meta/saimetadata.h:516:20: warning: 'sai_metadata_get_dash_acl_rule_action_name' initialized and declared 'extern'
  516 | extern const char* sai_metadata_get_dash_acl_rule_action_name(
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../meta/saimetadata.h:517:10: error: 'sai_dash_acl_rule_action_t' was not declared in this scope
  517 |     _In_ sai_dash_acl_rule_action_t value);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../meta/saimetadata.h:528:20: warning: 'sai_metadata_get_direction_lookup_entry_action_name' initialized and declared 'extern'
  528 | extern const char* sai_metadata_get_direction_lookup_entry_action_name(
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../meta/saimetadata.h:529:10: error: 'sai_direction_lookup_entry_action_t' was not declared in this scope
  529 |     _In_ sai_direction_lookup_entry_action_t value);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
In currernt build structure, when compiling the code, it depends on the installed SDK and local generate header files.
One of the header is saimetadata.h
After add the dash APIs, those new APIs in the new added folder not appeared in the SDK, but just defined in the local SAI source code.
Then those source code included in the sai_rpc_frontend.cpp.
Considering we will always use the latest header definiation from Official SAI repo but not with specific SDK, move the depends on SAI source code.

How
Remove the depends on the SDK installed headers

Verify
Build with local buildimage container.
Install the buildout artificates and run SAI test with it.

Signed-off-by: richardyu-ms <richard.yu@microsoft.com>